### ISSUE TITLE
workspace-name

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/deepin-wm#1]
Currently the workspace names are displayed like "1-workspace", "2-workspace" ...
This seems kind of odd.
It should be "workspace 1", "workspace 2" ...

**Comment by sonald** [comment]
Actually it is by design, although it looks odd. The rule is if you ever edit the workspace name (e.g workstation for #2), we'll show it like '2 workstation'，else, we give it a default display name like '2-workspace'.

**Comment by sonald** [comment]
there is a discussing undergoing, this design might change in the future. I'll just close it for now.

**Comment by mank319** [comment]
I agree with @oberon2007 :wink:

**Comment by sonald** [comment]
I agree with you guys too, but I've to stick to the designer's.

**Comment by manateelazycat** [comment]
In Deepin WM 2.0, we will delete workspace name feature, and instead better UI design to resolve this problem.

Thanks for report!
