### ISSUE TITLE
rename all the gala files to something else?

### ISSUE THREAD

**Issue by SolarAquarion** [linuxdeepin/deepin-wm#10]

**Comment by sonald** [comment]
Why? Did you have problem of installing deepin-wm and gala at the same time ?

**Comment by SolarAquarion** [comment]
Yes due to desktop files

**Comment by sonald** [comment]
ok, gonna fix that later. I never thought that deepin-wm and galawould co-exist.

**Comment by SolarAquarion** [comment]
@sonald they can on arch and should
