### ISSUE TITLE
Gala-Wayland in data is not  needed in the package

### ISSUE THREAD

**Issue by SolarAquarion** [linuxdeepin/deepin-wm#11]

**Comment by sonald** [comment]
can you plz be more specific?

**Comment by SolarAquarion** [comment]
gala-wayland.desktop

**Comment by SolarAquarion** [comment]
@sonald 

error: failed to commit transaction (conflicting files)
gala-bzr: /usr/share/applications/gala-wayland.desktop exists in filesystem
Errors occurred, no packages were upgraded.
==> WARNING: Failed to install built package(s).
gala-bzr

**Comment by sonald** [comment]
This has been taken care of at the tip of master branch.
