### ISSUE TITLE
building issue 

### ISSUE THREAD

**Issue by SolarAquarion** [linuxdeepin/deepin-wm#12]
Utils.vala:137.13-137.32: error: The name `DrawingService' does not exist in the context of `Gala.Plank'
					icon = Plank.DrawingService.get_icon_from_gicon (appinfo.get_icon ());
					       ^^^^^^^^^^^^^^^^^^^^
Utils.vala:145.15-145.34: error: The name `DrawingService' does not exist in the context of `Gala.Plank'
						image = Plank.DrawingService.load_icon (icon, size, size);
						        ^^^^^^^^^^^^^^^^^^^^
Utils.vala:212.29-212.48: error: The name `DrawingService' does not exist in the context of `Gala.Plank'
                    image = Plank.DrawingService.ar_scale (image, size, size);
                            ^^^^^^^^^^^^^^^^^^^^
Granite/Widgets/Utils.vala:279.23-279.48: warning: GLib.Settings.list_schemas has been deprecated since 2.40
Compilation failed: 3 error(s), 7 warning(s)
make[2]: *** [Makefile:1193: libdeepin_wm_la_vala.stamp] Error 1
make[2]: Leaving directory '/home/solaraquarion/deepin-wm/lib'
make[1]: *** [Makefile:489: all-recursive] Error 1
make[1]: Leaving directory '/home/solaraquarion/deepin-wm'

**Comment by sonald** [comment]
so what is the version of libplank in your system
