### ISSUE TITLE
tiling commands

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/deepin-wm#13]
Is there a way to trigger the tiling left and right of windows with a command, so it can be use with keyboard shortcuts?

**Comment by sonald** [comment]
AFAIK no. tiling is kind of a mouse behaviour.

**Comment by sonald** [comment]
with the tip of wm, you can do this by dbus message `qdbus com.deepin.wm /com/deepin/wm  com.deepin.wm.TileActiveWindow 1/2`

**Comment by Foxei** [comment]
I am using Deepin for a while and i'm a pure keyboard guy. And i think this is highly necessary and simply for the reason that there is already a command to do so. Why not adding a shortcut?

And yes i know about custom shortcuts.

**Comment by aiamuzz** [comment]
> with the tip of wm, you can do this by dbus message `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 1/2`

the command has stopped working ... no longer tiling the window as its supposed to ... 

@sonald  ... could you help with the correct commands to tile windows to the right and left ?

**Comment by sonald** [comment]
@aiamuzz actually it works. there must be something wrong with your environment...

**Comment by aiamuzz** [comment]
> @aiamuzz actually it works. there must be something wrong with your environment...

@sonald  ...
any way i can check what the problem could be ?

```
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 1/2
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 2/2
```

I have created custom keyboard shortcuts for the above commands separately ... shouldn't invoking the shortcuts tile the window to the right or left ... but instead it does nothing, no effect ... 

**Can this officially be included as a system shortcuts for WM ???**

**Comment by sonald** [comment]
I believe there are two gestures (two finger swipe left/right I guess ?) to activate tiling. 
you try if any other dbus methods can work.
and lastly invoke `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.ToggleDebug `, which will turn on the wm debug logging. then try to call `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 1/2` again.  all activities should be recorded at log file /tmp/mutter-`pidof deepin-wm`-XXXXXX

**Comment by sonald** [comment]
@aiamuzz sorry for the delay, I'm quite busy these days. I see nothing weird in the log file. just to be clear here. 
1.  check if `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.PerformAction 1` works.
2. Does drag window to the left/right border of the screen activate tiling?
3. what is the resolution of your monitor? or do you have dual monitors ?

**Comment by aiamuzz** [comment]
> `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.PerformAction 1`

seems to be the command to display workspace ... and its working fine.

> Does drag window to the left/right border of the screen activate tiling?

Yes its working ...

> what is the resolution of your monitor? or do you have dual monitors ?

single laptop monitor ... resolution 1366x768

**Comment by sonald** [comment]
that's quite weird.... and what are the versions of deepin-wm and libdeepin-mutter0g.

**Comment by aiamuzz** [comment]
hmmmm ...

```
deepin-wm is already the newest version (1.9.31-1).
libdeepin-mutter0g is already the newest version (3.20.34-1).
```

@sonald ... can you please upload a screen recorder(gif format) here ... i just want to see if i am doing something wrong or differently ?

**Comment by sonald** [comment]
@aiamuzz use `xprop` to find out the min size request for the specific window.  
e.g. on my setup, dde-file-manager set this 
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
        user specified location: 1200, 573
        user specified size: 1439 by 1062
        program specified minimum size: 1155 by 810
        program specified resize increment: 1 by 1
        program specified base size: 180 by 180
        window gravity: Static
```

Your monitor's size is  1366x768, and tiling works only when min width is less than half of the monitor with (1366/2).

**Comment by aiamuzz** [comment]
well honestly i didn't understand what you are trying to say ... but never the less please find the relevant data after running `xprop` and clicking on an open dde-file-manager ...

restore window size readings of dde-file-manager ...
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 29, 16
		user specified size: 1308 by 767
		program specified minimum size: 770 by 540
		program specified resize increment: 1 by 1
		window gravity: Static
```

**Comment by aiamuzz** [comment]
> as you can see, dde-file-manager set min size as 770x540, your screen resolution is 1366x768. wm will do the math 770 < 1366/2 before tiling and it's false. so no tiling is allowed at all. only when min width is less than 1366/2, can you tile your window.

I am still not able to wrap my head around the concept of 'minimum width' in relation to the whole tiling thing ... 

so to understand things in a simple way ... does it mean the tiling command will never work on my screen ... it does work when i drag the window with the cursor to the right or left ...

I hope there is some way i can modify something to get it working ?
If so please guide me to the said modifciation ... **i really want to be able to tile the windows left or right through a keyboard shortcut and this command in a working state is the only way to do it ... until deepin incorporates the tiling command as part of its default list of keyboard shortcut list.**

**Comment by sonald** [comment]
@aiamuzz I've been on a vacation last week. I do not know what's going on here now if you can not find `com.deepin.wrap.gnome.mutter.keybindings`. it must exists. @felixonmars

**Comment by aiamuzz** [comment]
> @aiamuzz I've been on a vacation last week. I do not know what's going on here now if you can not find com.deepin.wrap.gnome.mutter.keybindings. it must exists. @felixonmars

@sonald ... sorry my bad ... i had dconf flatpak version which did not pick the path to mutter keybindings.

I installed the non-flatpak version of the same and i could find the desired setting and set a shortcut for tiling left and right ... its working !!!

thanks for the assistance.

**Comment by sonald** [comment]
so everything is gonna flatpaked ? IMHO, this causes more problems than it provides.

**Comment by aiamuzz** [comment]
> so everything is gonna flatpaked ? IMHO, this causes more problems than it provides.

hahahaha ... i know ... programs like dconf on flatpak may not work full potentials ...

> And I still don't get why tiling by dbus won't work...

hmmmmmmm ... yeah ... could you get the tiling to work on your system and paste the same command here ? ... i can run the exact same command on my system ...

**Comment by sonald** [comment]
the command is the same as you pasted before. something else is wrong. need to dig deeper when I get time.

**Comment by aiamuzz** [comment]
> the command is the same as you pasted before. something else is wrong. need to dig deeper when I get time.

sure ... let me know when and what to dig out of my system ...

**Comment by annymosse** [comment]
how to split window horizontally or vertically via the terminal ?
