### ISSUE TITLE
High CPU usage in VirtualBox

### ISSUE THREAD

**Issue by x1596357** [linuxdeepin/deepin-wm#15]
Installed in virtualbox 5.1.22 as guest on Windows 10 15063 x64 host and Deepin Linux is updated to latest version(up to date 2017-06-17). `deepin-wm` can completely consume one of the cpu core, causing GUI lags and high CPU usage. In perf top, `copy_user_generic_string` is showed as the top of usage function. Killing deepin-wm can help for a while but it will repeat it again very soon.   
![1](https://user-images.githubusercontent.com/5744506/27254281-0bbadfec-53b8-11e7-801f-1d09f46c6edd.png)
![2](https://user-images.githubusercontent.com/5744506/27254280-0ba84724-53b8-11e7-90b1-0a05e178d198.png)

**Comment by sonald** [comment]
deepin-wm requires direct rendering capable environment. (check out `xdriinfo` output). vmware has no problem of rendering 3d apps. I'm not sure VB is capable of that.  Press win+shift+tab to use alternative wm (deepin-metacity) temporarily.

**Comment by x1596357** [comment]
```
$ xdriinfo
libGL is too old.
$ uname -a
Linux eric-pc 4.9.0-deepin5-amd64 #1 SMP PREEMPT Deepin 4.9.8-5 (2017-05-02) x86_64 GNU/Linux
```
To my understanding, if this is because of VirtualBox not capable of 3d rendering. It should be high CPU usage all the time. I come across this behavior often when I open a terminal doing something, and then CPU usage will at some point go high and never go down unless I kill it.

**Comment by sonald** [comment]
`xdriinfo` gives a hint. There is something wrong with your xorg video driver. My guess is that you got a NV card and tried to install nvidia driver ?

**Comment by x1596357** [comment]
No. I use VirtualBox on a laptop with a Intel integrated graphic card and a Nvidia 940M. I think VBox is using the Intel integrated graphic card and not using the other one. One thing that I did that concerns GPU maybe that I installed VBox Guest Additions.

**Comment by x1596357** [comment]
use `update-alternatives --config x-window-manager` and choose deepin-metacity and press `win + shift + tab` seems to help. Thanks. At least deepin-wm is not running.

**Comment by sonald** [comment]
without working direct rendering, there's no way to run deepin-wm correctly. VB's virtual video driver seems not suitable for 3d.
