### ISSUE TITLE
Feature request: Advancing with arrows while ALT+Tab

### ISSUE THREAD

**Issue by dimitrov-adrian** [linuxdeepin/deepin-wm#19]
Moving between windows with keyboard arrows while ALT+Tab

**Comment by aiamuzz** [comment]
how about .. arrow key control in **"Display windows in this workspace"** as well as in **"Display windows from all workspaces"** ... hope its not too difficult to implement these 2 features as you have already implemented it in **"Workspace View"** ... 'tab' button to navigate through windows of a given workspace & the right and left arrow keys help navigate between different workspaces.

**Comment by aiamuzz** [comment]
https://github.com/linuxdeepin/deepin-wm/issues/20

**Comment by sonald** [comment]
impled.

**Comment by aiamuzz** [comment]
Hi,

i recently updated my OS, can't find this implemented ... can you please confirm if this implementation is already pushed in the updates, if not when can we expect ?

**Comment by bocekm** [comment]
This hasn't been implemented till now.

**Comment by sonald** [comment]
@bocekm  which version of deepin-wm and linux distribution do you use ? I can confirm that deepin-wm 1.9.35 works fine.
