### ISSUE TITLE
Window maximizing, closing and snapping is not animated

### ISSUE THREAD

**Issue by mank319** [linuxdeepin/deepin-wm#2]
First of all I'd like to thank you for this awesome window manager!
I've been running it on my Arch installation for 2 days now and I really, really like it :+1:

I have recognized one thing that I would like to report:
When maximizing, closing or snapping a window, the operation is performed instantly without animation.
If this is not the intended behaviour (which I can hardly believe), it is probably an [upstream `gala` bug](https://bugs.launchpad.net/gala/+bug/1535018) so we should keep en eye on `gala`'s bugtracker to merge any potential fixes and vice versa propose potential fixes to them.

**Comment by sonald** [comment]
Thanks and yes, that's a bug of gala since I recently merged upstream gala. I'm planning of fixing these after spring vacation.

**Comment by mank319** [comment]
By the way: If you fix this and create an upstream pull request, make sure to claim your [bounty](https://www.bountysource.com/issues/29946715-no-un-maximize-snap-or-minimize-animations) :wink:

**Comment by sonald** [comment]
this has been fixed by commit af810a82

**Comment by mank319** [comment]
Awesome  :+1: it is great to have maximize/unmaximize animations again. Thanks @sonald :wink: 

Before you completely close this issue, I'd just like to point out that two actions are still lacking animations:
1) Snapping windows to the edge/top (top should be easily fixable by invoking maximize effect, right?)
2) Minimizing windows (to the dock)

**Comment by sonald** [comment]
1. I'm aware of that, will be fixed later. 
2. minimizing to the dock needs support of dock, this'll be supported soon by the dock.
stay tuned :smile:

**Comment by sonald** [comment]
@mank319 FYI, tiling preview has been added, and minimizing to dock icon is finished (cooperate with dde-dock)
