### ISSUE TITLE
Feature request: Option to move window controls to left

### ISSUE THREAD

**Issue by dimitrov-adrian** [linuxdeepin/deepin-wm#23]
Right now window controls are on right. It will be good to have option to move the controls on the left side. I tried with settings in the dconf-editor but it doesn't affect all apps but just some. File manager for example is one of them.

**Comment by sonald** [comment]
I'm afraid it's impossible right now  @manateelazycat @hualet   @zccrs

**Comment by hualet** [comment]
Sorry, but it won't be implemented.
