### ISSUE TITLE
Xorg variant removed when session ends

### ISSUE THREAD

**Issue by pyfection** [linuxdeepin/deepin-wm#26]
I have installed Deepin with Architect on two very different machines and have encountered the same issue. Every time I lock the screen, suspend or otherwise terminate the session, my Programmer Dvorak variant of the US layout gets removed and I have to enable it manually after logging back in with "setxkbmap -variant dvp" after which it works fine again. This is very annoying, so I hope you can fix it or provide me with a work around. Otherwise, Deepin is my favorite DE, so keep up the good work!

**Comment by sonald** [comment]
I believe this is not a problem of deepin-wm. can you post it to https://github.com/linuxdeepin/developer-center/issues ?
