### ISSUE TITLE
LibreOffice password promp falls outside the screen

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/deepin-wm#29]
https://youtu.be/pD0QokET0q4

**Comment by sonald** [comment]
It looks like a libreoffice problem to me. and I can not reproduce this problem with deepin 15.5 and libreoffice 5.4.0-1deepin.

**Comment by es20490446e** [comment]
My LibreOffice version was 6.0.1. I will report it to its developers.

**Comment by es20490446e** [comment]
Moved to the [LibreOffice Bug Tracker](https://bugs.documentfoundation.org/show_bug.cgi?id=115964). Thanks for the help.
