### ISSUE TITLE
update of gnome-desktop to 3.28 broke deepin-wm

### ISSUE THREAD

**Issue by carlocastoldi** [linuxdeepin/deepin-wm#30]
Basically the title.

Both my systems with arch linux and DDE broke updating the system to gnome 3.28. To update the system it was required to downgrade deepin-wm to 1.9.23-2 and deepin-mutter to 3.20.28-2.

Afterwards i went back to gnome-desktop 3.26.2-2, deepin-wm 1.9.24-1, deepin-mutter 3.20.29-1 and everything went back to normal

**Comment by disconsented** [comment]
I can confirm this as well

**Comment by carlocastoldi** [comment]
Ok apparently that was an Arch package issue. Sorry for the inconvenience!
You can close this issue ticket now
