### ISSUE TITLE
ALT + Left mouse button to drag window

### ISSUE THREAD

**Issue by david-barbion** [linuxdeepin/deepin-wm#31]
Hello,

Dragging window by pressing ALT + LMB is not working. I did not find any way to enable it.
Would-it be possible to add it as a new feature?

**Comment by sonald** [comment]
gsettings set com.deepin.wrap.gnome.desktop.wm.preferences mouse-button-modifier '<Alt>'

**Comment by david-barbion** [comment]
Fabulous! It works.

**Comment by ibrokemypie** [comment]
Is there any way to use this to also resize when dragging with right click, such as on i3?

**Comment by sonald** [comment]
@ibrokemypie try this ? `gsettings set com.deepin.wrap.gnome.desktop.wm.preferences resize-with-right-button true`

**Comment by aiamuzz** [comment]
I am missing something here ... 

@ibrokemypie  ... can you please describe ... this option ... dragging which window to where ?

is it dragging a window from the desktop to a workspace on the left or right ?

**Comment by ibrokemypie** [comment]
Yes, while holding a key and right clicking anywhere on a window, then dragging inwards or outwards, the window get shrunk or expanded, so you dont need to find and click tiny borders

**Comment by aiamuzz** [comment]
> Yes, while holding a key and right clicking anywhere on a window, then dragging inwards or outwards, the window get shrunk or expanded, so you dont need to find and click tiny borders

oh right ... is this working after running the suggest command sonald just provided ?

**Comment by aiamuzz** [comment]
oh yeah cool ... its working ... another productive feature to have learnt today !!!

I was missing the Alt mouse drag option ... glad i got it back along with an additional bonus feature !!!

thanks  to both of you ... @ibrokemypie ... @sonald  ... 

hahahahahaha
