### ISSUE TITLE
Wakeup from suspend destroys login

### ISSUE THREAD

**Issue by Faizanf33** [linuxdeepin/deepin-wm#32]
I'm using Hp AMD Radeon HD 8400 / R3 Series,
From the day i installed deepin, suspend mode is a problem for me,
the only solution i came up with was not to use suspend.
Pl. fix this problem as soon as possible

**Comment by sonald** [comment]
this is not the problem of deepin-wm. plz report it to [here](https://github.com/linuxdeepin/developer-center/issues)

**Comment by sonald** [comment]
this is usually a typical graphics driver issue.
