### ISSUE TITLE
New window pop up effects prevent wine steam's menu from working properly

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/deepin-wm#5]
<a href="https://github.com/felixonmars"><img src="https://avatars.githubusercontent.com/u/1006477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @felixonmars**
_Thursday Nov 26, 2015 at 03:40 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/124_

---

They also delay windows like fcitx's candidate window. I hope there is a way to disable pop up effects for certain classes of windows.

**Comment by sonald** [comment]
我没觉着fcitx的candidate window慢了啊，它的类型是UTILITY，wm里这个类型没show的动画。如果是各种menu类型，可以通过gsettings来控制，把相应的duration设置为0就没有动画了。
```
com.deepin.wrap.pantheon.desktop.gala.animations open-duration 350
com.deepin.wrap.pantheon.desktop.gala.animations snap-duration 250
com.deepin.wrap.pantheon.desktop.gala.animations close-duration 300
com.deepin.wrap.pantheon.desktop.gala.animations menu-duration 150
com.deepin.wrap.pantheon.desktop.gala.animations minimize-duration 1000
com.deepin.wrap.pantheon.desktop.gala.animations workspace-switch-duration 300
```

**Comment by felixonmars** [comment]
我这里 fcitx 的 candidate window 还是有个明显的 show 的动画 :(

**Comment by fasheng** [comment]
不应该啊, 我这边没问题
```
gsettings set com.deepin.wrap.pantheon.desktop.gala.animations menu-duration 0
```

**Comment by felixonmars** [comment]
@sonald fcitx 的没问题，但是 steam 的一直有问题……
