### ISSUE TITLE
Move window with ALT+CLICK

### ISSUE THREAD

**Issue by scorninpc** [linuxdeepin/deepin-wm#51]
It's possible implement ALT+Click on anyware of window to move that? It's so produtive

**Comment by BLumia** [comment]
There are some related *gsettings* keys under `org.gnome.desktop.wm.preferences`, they are`mouse-button-modifier`, `resize-with-right-button`. You can use `gsettings set` or `dconf-editor` to set these preferences, for your case, `mouse-button-modifier` set to `<Alt>`, and `resize-with-right-button` to `true`.

We are planning to switch to KWin btw :)

**Comment by scorninpc** [comment]
Exactly what i mean. You guys are the best
