### ISSUE TITLE
Desktop crash caused by deepin-wm

### ISSUE THREAD

**Issue by mengshengwu** [linuxdeepin/deepin-wm#60]
The deepin desktop is often stuck, the mouse can't click, but it can be slid. In addition to switching the tty shortcuts, the rest are all invalid. The deepin-wm process can be restored under other ttys. Later, closing windows effcet will not cause this problem, but not It’s a bit ugly to open the desktop.
![image](https://user-images.githubusercontent.com/37139489/61572997-e4841f80-aad9-11e9-8f77-51367b1de9c9.png)

**Comment by BLumia** [comment]
Hi and since deepin-wm now no longer have any official support from Deepin, maybe it's time to install deepin-kwin and try it out?

btw for your issue, you can install systemd-coredump (not quite sure the package name on manjaro) package and provide the coredump stacktrace via `coredumpctl info <pid>` (pid can be seen via `coredump list`) so others may be able to help you out.

**Comment by mengshengwu** [comment]
> Hi and since deepin-wm now no longer have any official support from Deepin, maybe it's time to install deepin-kwin and try it out?
> 
> btw for your issue, you can install systemd-coredump (not quite sure the package name on manjaro) package and provide the coredump stacktrace via `coredumpctl info <pid>` (pid can be seen via `coredump list`) so others may be able to help you out.

Thank you for your reply. I have installed deepin-kwin, the perfermance of  it is not bad, but i didn't find any settings to change the position of the navigate button(maybe call other name, it's the top button of window) from left to right.
At last thank you so much !!

**Comment by BLumia** [comment]
Hi and could you provide a screenshot for your issue? If you means the close window button, maximum and minimum button, it should be on the top-right side of the window by default.

You can (and it's recommended to) open another issue (at [Developer Center](https://github.com/linuxdeepin/developer-center)) to discuss this question, btw :)

**Comment by mengshengwu** [comment]
Thank you for your reply. I just switch to `deepin-wm`  in the day before yesterday because I am not used to using the switch window of  `deepin- kwin`. but fortunately, I didn't find any crash problem like before until now.  Thanks  for your help !!   :)

**Comment by BLumia** [comment]
FYI if you are using `deepin-kwin`, you can also tweak some of the kwin behaviors via [`systemsettings`](https://www.archlinux.org/packages/extra/x86_64/systemsettings/) which include the task switcher appearance :)
