### ISSUE TITLE
deepin-wm总是造成桌面卡死

### ISSUE THREAD

**Issue by mengshengwu** [linuxdeepin/deepin-wm#61]
+ 环境：
![image](https://user-images.githubusercontent.com/37139489/62917466-f69e6880-bdce-11e9-882c-49a7300b4225.png)

+ 问题： 正常使用情况下界面突然卡死，只有鼠标的光标能滑动， 但是点击没有效果，除了切换tty其余快捷键全失效。 切换到其他tty  kill 掉deepin-wm的进程 切换回来就恢复没有开Windows Effect的状态。 以及切换回来刚才关闭chrome的时候， 弹出一个报错框提示信息是 deepin-wm crashed by issues #60 
+ 补充： 上次我写了这个 issues#60, 我看了论坛里不少人也有这些问题， 但是给出的方法都是指标不治本的方法，重启deepin-wm什么的， 大佬给了装kwin的建议，但是效果不如deepin-wm好啊, 设置之后快捷键不少都失效。需要什么日志文件的话， 请告诉我一下路径， 实力还比较差，不然想贡献一份力量。

**Comment by BLumia** [comment]
Deepin 官方已经停止了对 deepin-wm 的维护（但可能仍有部分发行版默认安装 deepin-wm），请考虑切换至 deepin-kwin 。

另外对于 kwin 的一部分行为，可以通过安装 systemsettings5 （我没查在 manjaro 上的包名）并在里面找到一些对应的设置选项。需要注意的是，deepin-kwin 和 kwin 本身还是有些区别的（比如 deepin 目前使用自己的窗口装饰插件，和 systemsettings5 中【应用程序风格>窗口标题的观感】的设置是不对应的）。

不过还是提一下，超出控制中心之外的任何配置都是不受支持的，请明确需求按需配置。

> 但是效果不如deepin-wm好啊, 设置之后快捷键不少都失效。

可以提供一下具体信息吗？设置了怎样的快捷键之类。对于 deepin-kwin 的问题，可以直接提 issue 以便我们改善它。

进一步的 issue 可以考虑提到 [DeveloperCenter](https://github.com/linuxdeepin/developer-center) :)

**Comment by mengshengwu** [comment]
好的 谢谢！！
