### ISSUE TITLE
显存/内存占用高 High GPU/RAM Usage

### ISSUE THREAD

**Issue by MidoriYakumo** [linuxdeepin/deepin-wm#62]
版本：1.9.35-1
显卡信息：
| NVIDIA-SMI 390.67                 Driver Version: 390.67                    |
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
4k显示器下窗口管理器经常占用超过800M的显存和内存，Xorg资源占用也很高，有时还会内存/显存泄露，连续使用数天会自行崩溃

**Comment by BLumia** [comment]
请考虑切换到 dde-kwin ，deepin-wm 已被其替换且 deepin-wm 目前已不再维护 :(
