### ISSUE TITLE
窗口内容模糊闪烁 Window content get blurred

### ISSUE THREAD

**Issue by MidoriYakumo** [linuxdeepin/deepin-wm#63]
版本：1.9.35-1
显卡信息：
| NVIDIA-SMI 390.67                 Driver Version: 390.67                    |
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
在某些应用程序中会出现如下现象，关闭wm后显示正常
![深度录屏_deepin-system-monitor_20190903114514](https://user-images.githubusercontent.com/6872220/64142863-63da7200-ce40-11e9-8432-50b2851f4a68.gif)

**Comment by BLumia** [comment]
请考虑切换到 dde-kwin ，deepin-wm 已被其替换且 deepin-wm 目前已不再维护 :(

**Comment by MidoriYakumo** [comment]
@BLumia any guide for shipping from dde-wm to dde-kwin? The default wm in my distro is still dde-wm, not sure how KDE framework affect on the desktop environment.

**Comment by BLumia** [comment]
> The default wm in my distro is still dde-wm

But you doesn't even mention which distro you're using...

Deepin distro already start vendor dde-kwin by default. Assume you are using Arch, you can then install the `deepin-kwin` package and next time you login a DDE session, it should be using dde-kwin automatically. If you are using other distro, please leave more details so we can offer more help.
