### ISSUE TITLE
Updating from 1.9.38-1 to 1.9.38-2 breaks  deepin desktop

### ISSUE THREAD

**Issue by abrahammurciano** [linuxdeepin/deepin-wm#64]
I'm running Arch Linux with deepin desktop installed, and when I upgrade any of the following three packages, the next time I boot my computer, deepin desktop shows no taskbar, the theme looks completely wrong, and the wifi stops working (the wifi may not be your problem, because it gives me issues in general).

These are the packages that break when upgraded:
```
deepin-mutter: 3.20.38-2	# was on v3.20.38-1
deepin-wm: 1.9.38-2		# was on v1.9.38-1
gnome-desktop: 1:3.34.0-1	# was on v1:3.32.2-1
```
I would love to help solve this issue, so if there's any terminal outputs you'd like me to post here, just let me know.

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/1552

Not sure if @sonald still would like to maintain the deepin-wm codebase :/

The old deepin-wm is deprecated and please consider install `deepin-kwin` package, DDE will use the new wm(dde-kwin) automatically next time you login into a new DDE session :)

**Comment by aiamuzz** [comment]
> Not sure if @sonald still would like to maintain the deepin-wm codebase :/

It would be a shame to lose out on a picture perfect original UI/UX of Deepin that drew our attention to Deepin ... if not for Deepin-WM ... i doubt if i would have been drawn to it ...

@sonald ... wish you adopted it ... and kept it maintained for its current functionality and feature set ... honestly it had been perfected ... and did not really require any more work !!!

**Comment by sonald** [comment]
just got a lot of business trips these days, and I'll handle it after national day.

**Comment by abrahammurciano** [comment]
> @sonald ... wish you adopted it ... and kept it maintained for its current functionality and feature set ... honestly it had been perfected ... and did not really require any more work !!!

This!! Couldn't have said it better myself. deepin-wm is honestly the **BEST** wm I've seen on Linux, especially compared to kwin... Ughh I hate everything k, such bad design... I has to leave mutter, wm, and gnome desktop on older versions (I know that's a bad idea, but desperate times...) just to avoid switching wm. Please do the Linux world a favour by keeping deepin-wm around

**Comment by sonald** [comment]
By switching to modern kwin, we keep our tech stack consistent. We'll try to port most of deepin-wm's best design into dde-kwin and make some new changes over the course of V20 development cycle.

**Comment by aiamuzz** [comment]
> By switching to modern kwin, we keep our tech stack consistent. We'll try to port most of deepin-wm's best design into dde-kwin and make some new changes over the course of V20 development cycle.

@sonald ... is it too much work to just preserve (freeze) the current state of Deepin-WM ... **like a good piece(rather proud piece) of History of Linux Deepin ... a history that drew thousands like us to this operating system ...** with efforts from your end ONLY to keep it functional on all future updates of Linux Deepin ???

**Comment by DasJott** [comment]
@aiamuzz I installed the new deepin-kwin as well, because I had the same issues @abrahammurciano had. I must say, it is not any different in look and feel. It is still a little buggy, that needs to be said, but it (fortunately) does **not** introduce any K into deepin. 

Btw: I also hate the KDE look. Always loved Gnome and also Unity on Ubuntu a while ago, until they changed everything. Then I was looking for something new and fell in love with deepin.
Best WM in my opinion. Sometimes buggy but mostly just cool!

**Comment by aiamuzz** [comment]
> Then I was looking for something new and fell in love with deepin.
> Best WM in my opinion. Sometimes buggy but mostly just cool!

@dasjott ...
did you move to Linux Deepin before Kwin was implemented here or after ... we were all attracted to Deepin-WM ... that drew us to Linux Deepin ... so having used Deepin-WM for more than 2 years ... we know Kwin is still a looooooong way to the elegance and simplicity of Deepin-WM ... hence the expression of nostalgia and urge to save it to posterity(rather then let it die) ... by freezing its development(cos it was already perfected) ... We hope it will just be maintained to run ok on all future updates/upgrades of Linux Deepin ... just maintain as is !!!

a second choice to all those users who love it who run non-Nvidia hardware on which it had no issues whatsoever !!!

**Comment by abrahammurciano** [comment]
@aiamuzz idk when kwin was implemented, I installed arch Linux a few weeks ago, and that's when I discovered deepin desktop. When I installed it it came with deepin-wm so I liked it and kept it. When it stopped working and I installed kwin, the look drastically changed. If I would have to use kwin, I think I'd just switch to some other DE... Which would be a pity, because my favourite so far is deepin with deepin-wm

**Comment by aiamuzz** [comment]
> When I installed it it came with deepin-wm so I liked it and kept it. When it stopped working and I installed kwin, the look drastically changed.

exactly ... imagine you just used Deepin-WM for a few days or weeks ... and your reaction to kwin is "drastically changed" ... imagine we have been using it for years ... and the pain of losing it ... and seeing it die !!!

**Comment by DasJott** [comment]
> did you move to Linux Deepin before Kwin was implemented here or after
I moved from Ubuntu to Arch about 2 years ago and there I chose DDE and kept it.
A few days ago the dock disappered and the window effects stopped working. So I filed an issue here, where the answer was deepin-kwin. It solved the problems I had and I can work again.

> When it stopped working and I installed kwin, the look drastically changed. If I would have to use kwin, I think I'd just switch to some other DE... Which would be a pity, because my favourite so far is deepin with deepin-wm

Drastically? I don't see that. Yes, I still have problems with window titelbars not changing to numix theme anymore. Also some windows only resize on the one pixel thick border, which is annoying.
Everything is still a little buggy, I must confess.

deepin-wm was really a nice thing.I also have weird feelings about taking a K thing as a base for a new version....

**Comment by aiamuzz** [comment]
> deepin-wm was really a nice thing.I also have weird feelings about taking a K thing as a base for a new version....

"nice thing" ... that is why, can't watch it die ...
we don't mind it being kept on life long support with not a single feature upgrade ... if it just maintained as it is and ensure it runs on all future Linux Deepin updates/upgrades ... that is all we  ask !!!

> Drastically? I don't see that.

It is DRASTIC ... trust us ... we have been using it for a couple of years ... you know how i personally felt ... i am sure a lot of others felt emotions as strong ... It felt like i went to sleep with my lovely wife and woke up the next morning with a woman who wasn't my wife ... I just Shrieked ... panicked ... :fearful: ... i was in fact contemplating to move to Elementary ... until the Deepin Team assured us they will get the exact same UI/UX visually on kwin ... that is how i have been living(managing) to see the day my lovely wife will be returned  !!! :smile: 


the whole K thing is ugly and unpolished may be feature rich but certainly not elegant ... 

you know there is mutter ... and then there deepin-wm ... which is nothing but mutter ... 
i was using UbuntuGnome for more than a few years ... when i came across Linux Deepin i had no idea it was the same mutter i had been using on Ubuntu gnome ... that is the magic Deepin Team ( @shule ... ) had pulled ... 

I am just hoping they do the same with kwin when they're done improving kwin ... i just want it to be as un recognizable as mutter and deepin-wm-mutter ... but going by the response we've been having off late ... i am sceptical ... the teams decision off late have been unstable the way they are making drastic changes !!!

well hope is the only thing one can latch onto ...

**Comment by DasJott** [comment]
> the whole K thing is ugly and unpolished may be feature rich but certainly not elegant ...

Absoluetey! I also hate K... bloated and cold.

> It is DRASTIC ... trust us ... we have been using it for a couple of years 

Me too. Two years of deepin-wm. Where are that drastic changes exactly?

> i was using UbuntuGnome for more than a few years

I was using gnome for around 8 years before I switched to unity (because Ubuntu did so).

I also hope that the move to K world will not end up being like K ...

**Comment by aiamuzz** [comment]
> I also hope that the move to K world will not end up being like K ...
that is my worst fear too ...

> Me too. Two years of deepin-wm. Where are that drastic changes exactly?

i would show ... but Deepin Team is already irritated with this topic ... well simply put ... i miss the all workspace view with the workspaces on top and the open windows of that workspace on the rest of the screen ... the smoooth animations ... various shortcuts that enable navigating through the windows and workspaces ... it was fluid and elegant ...

kwin's current workspace view is a bland strip in the center of the screen ... with so much of screen real estate being wasted ... 

the beautiful tiling animation of windows views and the navigation using keyboard ... most elegant on Deepin-wm ...

kwin ... a bland windows views with windows just thrown on the the screen with no order or elegance or a design to it ... I can just go on and on ... i fear Deepin Team might just blacklist me on their repo's for feeling strongly and expressing so about Deepin-WM ... :laughing:  :rofl:

**Comment by gchamon** [comment]
As a developer myself I sympathise with the dev's push for newer tech. If they say, `deepin-wm` is harder to maintain, breaks after dependencies updates and hinders development, I believe we should all embrace something newer for the sake of the dev's sanity.

What deepin should push is towards porting look and feel of the legacy `deepin-wm` into `deepin-kwin`. I guess if it behaved the same we would be ok with it, and @sonald said already he intends to do this port, so lets be patient and help them with bug reports and encouragement, if we can't ourselves help with coding.

**Comment by DasJott** [comment]
@aiamuzz , @abrahammurciano 
After a while working with DDE on kwin I must confess that it clearly noticable got worse.
I filed a bunch of issues already. Window effects crash so that shadows are no shadows anymore but simply huge black borders, window chooser in dock is broken, some shortcuts do not work anymore, terminal resizing does not work anymore....
What a pity...

**Comment by sonald** [comment]
@DasJott  I'm not sure which version are you using ?  the work of porting deepin-wm has been undergoing these days, but the release date is not near yet. all ongoing changes will be shipped with our next big release v20.

**Comment by aiamuzz** [comment]
> the work of porting deepin-wm has been undergoing these days, but the release date is not near yet. all ongoing changes will be shipped with our next big release v20.

@sonald ... thanks a ton !!!
... as long as its not six feet under ... we are ok with it ... we just want it to be alive ... even if its not growing !!!

**Comment by aiamuzz** [comment]
@sonald ... i am happy the team(YOU) has considered keeping it alive ...

not with any intention to push the consideration ... just a thought ... would having a choice(a button(a switch)) in the Control Settings panel for users to choose between **DeepinWM** and **Deepin Kwin** be too much work ... it will add to the simplicity of use for new users ...

I have configured shortcuts to switch between the 2 ... so this thought was only to keep it simple and easy for non-techy savy users.

thanks.

**Comment by sonald** [comment]
> not with any intention to push the consideration ... just a thought ... would having a choice(a button(a switch)) in the Control Settings panel for users to choose between DeepinWM and Deepin Kwin be too much work ... it will add to the simplicity of use for new users ...

we may consider about it after v20 gets released. right now, we are working hard to match the schedule.

**Comment by aiamuzz** [comment]
> we may consider about it after v20 gets released. right now, we are working hard to match the schedule.

wow ... really ... thanks ... a switch in control panel settings would be the best way to keep DeepinWM alive ... its smoothness and handling of animations is hard to match even in kwin ... 

I'll be sure to remind you on this 'switch' feature after V20 is released and settled(stable) !!!

**Comment by franciscocpg** [comment]
> @sonald ... i am happy the team(YOU) has considered keeping it alive ...
> 
> not with any intention to push the consideration ... just a thought ... would having a choice(a button(a switch)) in the Control Settings panel for users to choose between **DeepinWM** and **Deepin Kwin** be too much work ... it will add to the simplicity of use for new users ...
> 
> I have configured shortcuts to switch between the 2 ... so this thought was only to keep it simple and easy for non-techy savy users.
> 
> thanks.

@aiamuzz 
Are you still able to use **DeepinWM**  with Arch Linux (isn't it broken?). If so, how did you get it?

**Comment by aiamuzz** [comment]
> > @sonald ... i am happy the team(YOU) has considered keeping it alive ...
> > not with any intention to push the consideration ... just a thought ... would having a choice(a button(a switch)) in the Control Settings panel for users to choose between **DeepinWM** and **Deepin Kwin** be too much work ... it will add to the simplicity of use for new users ...
> > I have configured shortcuts to switch between the 2 ... so this thought was only to keep it simple and easy for non-techy savy users.
> > thanks.
> 
> @aiamuzz
> Are you still able to use **DeepinWM** with Arch Linux (isn't it broken?). If so, how did you get it?

sorry i am not on Arch ... I am on Linux Deepin ...

**Comment by gchamon** [comment]
@franciscocpg I am on Arch Linux and last time `deepin-kwin` broke because `kwin` updated I just uninstalled `deepin-kwin` and reinstalled `deepin` and `deepin-extra`. With pacman that would be

    sudo pacman -Rcns deepin-kwin
    sudo pacman -S deepin deepin-extra

**Comment by franciscocpg** [comment]
> sorry i am not on Arch ... I am on Linux Deepin ...

Oh I see @aiamuzz 

I hope that the porting mentioned by @sonald is compatible with Arch Linux.

**Comment by franciscocpg** [comment]
> @franciscocpg I am on Arch Linux and last time `deepin-kwin` broke because `kwin` updated I just uninstalled `deepin-kwin` and reinstalled `deepin` and `deepin-extra`. With pacman that would be
> 
> ```
> sudo pacman -Rcns deepin-kwin
> sudo pacman -S deepin deepin-extra
> ```

@gchamon 
By doing so you have **DeepinWM** back on Arch Linux?

**Comment by gchamon** [comment]
`deepin-wm` is a dependency of `startdde` which is installed when you install `deepin` package, if I am not mistaken. If your problem is just a matter of dependency installation, this would be enough, but to be certain we would have to take a look at which kind of problems you are facing.

**Comment by franciscocpg** [comment]
The problems I'm facing are the same reported in this issue's' description: https://github.com/linuxdeepin/deepin-wm/issues/64#issue-496715898. The only way I found to fix it was by installing `deepin-kwin` as stated in https://github.com/linuxdeepin/deepin-wm/issues/64#issuecomment-533859708. But like mentioned in other comments, `deepin-kwin` is buggy compared to `deepin-wm` so I would like to use it until `deepin-kwin` gets more stable.

**Comment by felixonmars** [comment]
The problems you mentioned should have been fixed in 1.9.38-3 released on Oct 4.

**Comment by franciscocpg** [comment]
@felixonmars 

This means that I can use **DeepinWM** again on Arch Linux? If so, should I follow the steps mentioned in https://github.com/linuxdeepin/deepin-wm/issues/64#issuecomment-546912679?

Also, if the problems are fixed, shouldn't this issue be closed?

**Comment by felixonmars** [comment]
Indeed. I replied in https://github.com/linuxdeepin/developer-center/issues/1555 but forgot this one. Just remove deepin-kwin and reboot should be enough.

**Comment by franciscocpg** [comment]
Thank you @felixonmars.

I'll give it a try.

**Comment by DasJott** [comment]
I tried it and it works. Pretty good. 
The kwin substitue is simply far away from being finished by now....

**Comment by aiamuzz** [comment]
> ...  kwin substitue  ...
... i guess you mean deepinWM substitute(which is kwin) is far from finished ...

**Comment by aiamuzz** [comment]
> ...  kwin substitue  ...
... i guess you mean deepinWM substitute(which is kwin) is far from finished ...

**Comment by aiamuzz** [comment]
> ...  kwin substitue  ...

 ... i guess you mean deepinWM substitute(which is kwin) is far from finished ...
